"""schema: customers, vehicles, mechanics, tickets, assignments, inventory

Revision ID: 401ea178110b
Revises: 0001_init
Create Date: 2025-10-30 11:33:47.219979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401ea178110b'
down_revision = '0001_init'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mechanic',
    sa.Column('mechanic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('mechanic_id')
    )
    op.create_table('vehicle',
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('license_plate', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vin')
    )
    op.create_table('service_ticket',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('date_in', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_out', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', name='ticket_status_enum'), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['vin'], ['vehicle.vin'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('service_assignment',
    sa.Column('service_ticket_id', sa.Integer(), nullable=False),
    sa.Column('mechanic_id', sa.Integer(), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanic.mechanic_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_ticket_id'], ['service_ticket.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_ticket_id', 'mechanic_id')
    )
    op.create_table('ticket_inventory',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_ticket.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'inventory_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_inventory')
    op.drop_table('service_assignment')
    op.drop_table('service_ticket')
    op.drop_table('vehicle')
    op.drop_table('mechanic')
    op.drop_table('inventory')
    op.drop_table('customer')
    # ### end Alembic commands ###
