"""split models into package

Revision ID: 55a9560a9e13
Revises: e42b21bb6c94
Create Date: 2025-08-28 20:58:25.822649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a9560a9e13'
down_revision = 'e42b21bb6c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_inventory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ticket_inventory_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ticket_inventory_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory', ['inventory_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'service_ticket', ['ticket_id'], ['ticket_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ticket_inventory_ibfk_1'), 'inventory', ['inventory_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ticket_inventory_ibfk_2'), 'service_ticket', ['ticket_id'], ['ticket_id'])

    # ### end Alembic commands ###
