"""Fix ticket_inventory relationship

Revision ID: e42b21bb6c94
Revises: fa8b14213ea8
Create Date: 2025-08-14 13:11:18.405262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42b21bb6c94'
down_revision = 'fa8b14213ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_inventory',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_ticket.ticket_id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'inventory_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###
