"""add mechanic password_hash and unique email

Revision ID: 6beab10b4a8c
Revises: 55a9560a9e13
Create Date: 2025-08-28 22:44:13.990022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6beab10b4a8c'
down_revision = '55a9560a9e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
